<html>
  <head>
    <title>Table 1</title>
  </head>
  <body>
    <table
      border="1px"
      cellpadding="2px"
      cellspacing="0"
      width="40%"
      align="center"
    >
      <tr>
        <thead align="center">
          <td><h4>No</h4></td>
          <td><h4>Nama</h4></td>
          <td><h4>Nim</h4></td>
        </thead>
      </tr>
      <tbody>
        <tr>
          <td>1</td>
          <td>Siti</td>
          <td>34101043</td>
        </tr>
        <tr>
          <td>2</td>
          <td>Diki</td>
          <td>34101023</td>
        </tr>
      </tbody>
    </table>
  </body>
</html>